version = 0.1

[default.global.parameters]
stack_name = "todo-main-service"
region = "ap-southeast-1"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "todo-main-service"
disable_rollback = false
parameter_overrides = "AllowedOriginParam=\"https://d2wjdko2jskle3.cloudfront.net\" TodosTableName=\"Todos\" FilesTableName=\"TodoFiles\" FilesBucketName=\"todo-app-group10-backend\" SharedUserPoolId=\"ap-southeast-1_yZP3iSlwa\" SharedUserPoolClientId=\"6a716ppbifnvnecotqcv8vuoi3\""
image_repositories = []

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
